FROM ubuntu:20.04

RUN apt update && apt install software-properties-common -y && apt update && add-apt-repository ppa:ubuntu-toolchain-r/test && apt update && apt install gcc-9 libstdc++6 -y

WORKDIR /src/
ADD ./witness ./witness
